USE DATABASE RETAIL_DB;

CREATE OR REPLACE VIEW RETAIL_DB.ANALYTICS.VW_DAILY_SALES AS
SELECT
    SALE_DATE,
    SUM(AMOUNT) AS TOTAL_REVENUE,
    COUNT(*) AS TOTAL_ORDERS
FROM RETAIL_DB.CURATED.SALES
GROUP BY SALE_DATE;

CREATE OR REPLACE VIEW RETAIL_DB.ANALYTICS.VW_TOP_PRODUCTS AS
SELECT
    PRODUCT_ID,
    SUM(AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_DB.CURATED.SALES
GROUP BY PRODUCT_ID;

CREATE OR REPLACE VIEW RETAIL_DB.ANALYTICS.VW_TOP_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    SUM(AMOUNT) AS TOTAL_SPENT
FROM RETAIL_DB.CURATED.SALES
GROUP BY CUSTOMER_ID;