CREATE OR REPLACE VIEW ANALYTICS.VW_DAILY_SALES AS
SELECT
    SALE_DATE,
    SUM(AMOUNT) TOTAL_REVENUE,
    COUNT(*) TOTAL_ORDERS
FROM CURATED.SALES
GROUP BY SALE_DATE;

CREATE OR REPLACE VIEW ANALYTICS.VW_TOP_PRODUCTS AS
SELECT
    PRODUCT_ID,
    SUM(AMOUNT) TOTAL_REVENUE
FROM CURATED.SALES
GROUP BY PRODUCT_ID
ORDER BY TOTAL_REVENUE DESC;

CREATE OR REPLACE VIEW ANALYTICS.VW_TOP_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    SUM(AMOUNT) TOTAL_SPENT
FROM CURATED.SALES
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_SPENT DESC;