

USE DATABASE RETAIL_DB;

CREATE SHARE RETAIL_SHARE;

GRANT USAGE ON DATABASE RETAIL_DB
TO SHARE RETAIL_SHARE;

GRANT USAGE ON SCHEMA CURATED
TO SHARE RETAIL_SHARE;

GRANT SELECT ON TABLE CURATED.CUSTOMERS
TO SHARE RETAIL_SHARE;