NULL;
/*CREATE EXTERNAL TABLE EXT_SALES(ID NUMBER) LOCATION=@EXT_S3_STAGE;


CREATE STAGE EXT_S3_STAGE
URL='s3://retail-bucket/data';

CREATE EXTERNAL TABLE EXT_SALES
(
    SALE_ID NUMBER AS VALUE:SALE_ID::NUMBER,
    AMOUNT NUMBER AS VALUE:AMOUNT::NUMBER
)
LOCATION=@EXT_S3_STAGE;*/
