USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE RETAIL_WH
WAREHOUSE_SIZE='XSMALL'
AUTO_RESUME=TRUE
AUTO_SUSPEND=60;

CREATE DATABASE RETAIL_DB;

USE DATABASE RETAIL_DB;

CREATE SCHEMA RAW;
CREATE SCHEMA STAGE;
CREATE SCHEMA CURATED;
CREATE SCHEMA ANALYTICS