USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_RESUME = TRUE
AUTO_SUSPEND = 60;

CREATE DATABASE IF NOT EXISTS RETAIL_DB;

USE DATABASE RETAIL_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGE;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;