CREATE OR REPLACE TABLE CURATED.CUSTOMERS AS
SELECT DISTINCT
    CUSTOMER_ID,
    UPPER(NAME) NAME,
    LOWER(EMAIL) EMAIL,
    CITY
FROM RAW.CUSTOMERS;

CREATE OR REPLACE TABLE CURATED.SALES AS
SELECT *
FROM RAW.SALES;
