
USE DATABASE RETAIL_DB;

ALTER TABLE RAW.SALES
CLUSTER BY(SALE_DATE);

CREATE MATERIALIZED VIEW MV_DAILY_SALES AS
SELECT
    SALE_DATE,
    SUM(AMOUNT) TOTAL_SALES
FROM RAW.SALES
GROUP BY SALE_DATE;

ALTER TABLE RAW.CUSTOMERS
ADD SEARCH OPTIMIZATION;
