
USE DATABASE RETAIL_DB;

ALTER TABLE RAW.SALES
CLUSTER BY(SALE_DATE);




CREATE OR REPLACE DYNAMIC TABLE RETAIL_DB.CURATED.DT_DAILY_SALES
TARGET_LAG = '1 minute'
WAREHOUSE = RETAIL_WH
AS
SELECT
    SALE_DATE,
    SUM(AMOUNT) AS TOTAL_SALES
FROM RETAIL_DB.RAW.SALES
GROUP BY SALE_DATE;