USE DATABASE RETAIL_DB;
USE SCHEMA STAGE;

CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
TYPE = JSON;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FORMAT
TYPE = PARQUET;
