USE DATABASE RETAIL_DB;
USE SCHEMA STAGE;

CREATE STAGE IF NOT EXISTS CSV_STAGE
FILE_FORMAT = CSV_FORMAT;

CREATE STAGE IF NOT EXISTS JSON_STAGE
FILE_FORMAT = JSON_FORMAT;

CREATE STAGE IF NOT EXISTS PARQUET_STAGE
FILE_FORMAT = PARQUET_FORMAT;