USE DATABASE RETAIL_DB;
USE SCHEMA STAGE;

CREATE STAGE IF NOT EXISTS RETAIL_DB.STAGE.CUSTOMERS_STAGE
FILE_FORMAT = RETAIL_DB.STAGE.CSV_FORMAT;

CREATE STAGE IF NOT EXISTS RETAIL_DB.STAGE.PRODUCTS_STAGE
FILE_FORMAT = RETAIL_DB.STAGE.CSV_FORMAT;

CREATE STAGE IF NOT EXISTS RETAIL_DB.STAGE.STORES_STAGE
FILE_FORMAT = RETAIL_DB.STAGE.CSV_FORMAT;

CREATE STAGE IF NOT EXISTS RETAIL_DB.STAGE.SALES_STAGE
FILE_FORMAT = RETAIL_DB.STAGE.CSV_FORMAT;