CREATE TABLE IF NOT EXISTS RETAIL_DB.RAW.CUSTOMERS
(
    CUSTOMER_ID NUMBER,
    NAME STRING,
    EMAIL STRING,
    CITY STRING
);

CREATE TABLE IF NOT EXISTS RETAIL_DB.RAW.PRODUCTS
(
    PRODUCT_ID NUMBER,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER(10,2)
);

CREATE TABLE IF NOT EXISTS RETAIL_DB.RAW.STORES
(
    STORE_ID NUMBER,
    STORE_NAME STRING,
    CITY STRING
);

CREATE TABLE IF NOT EXISTS RETAIL_DB.RAW.SALES
(
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    STORE_ID NUMBER,
    AMOUNT NUMBER(10,2),
    SALE_DATE DATE
);