USE DATABASE RETAIL_DB;
USE SCHEMA STAGE;

COPY INTO STAGE.CUSTOMERS
FROM @RETAIL_STAGE/customers.csv;

COPY INTO STAGE.PRODUCTS
FROM @RETAIL_STAGE/products.csv;

COPY INTO STAGE.STORES
FROM @RETAIL_STAGE/stores.csv;

COPY INTO STAGE.SALES
FROM @RETAIL