USE DATABASE RETAIL_DB;
USE SCHEMA RAW;

COPY INTO RAW.CUSTOMERS
FROM @RETAIL_STAGE/customers.csv;

COPY INTO RAW.PRODUCTS
FROM @RETAIL_STAGE/products.csv;

COPY INTO RAW.STORES
FROM @RETAIL_STAGE/stores.csv;

COPY INTO RAW.SALES
FROM @RETAIL