USE DATABASE RETAIL_DB;
USE SCHEMA RAW;


COPY INTO RETAIL_DB.RAW.CUSTOMERS
FROM @RETAIL_DB.STAGE.CUSTOMERS_STAGE;

COPY INTO RETAIL_DB.RAW.PRODUCTS
FROM @RETAIL_DB.STAGE.PRODUCTS_STAGE;

COPY INTO RETAIL_DB.RAW.STORES
FROM @RETAIL_DB.STAGE.STORES_STAGE;

COPY INTO RETAIL_DB.RAW.SALES
FROM @RETAIL_DB.STAGE.SALES_STAGE;