
CREATE ROLE DATA_ENGINEER;
CREATE ROLE DATA_ANALYST;
CREATE ROLE DATA_SCIENTIST;

GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE DATA_ANALYST;

GRANT USAGE ON DATABASE RETAIL_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE DATA_ANALYST;

GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAIL_DB
TO ROLE DATA_ENGINEER;

GRANT SELECT ON FUTURE TABLES IN DATABASE RETAIL_DB
TO ROLE DATA_ANALYST;