
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS DATA_SCIENTIST;

CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH;

GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE DATA_ANALYST;
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE DATA_SCIENTIST;

GRANT USAGE ON DATABASE RETAIL_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE DATA_SCIENTIST;

GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAIL_DB
TO ROLE DATA_ENGINEER;

GRANT SELECT ON FUTURE TABLES IN DATABASE RETAIL_DB
TO ROLE DATA_ANALYST;
