
USE DATABASE RETAIL_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TASK SALES_TASK
WAREHOUSE=RETAIL_WH
SCHEDULE='5 MINUTE'
AS
INSERT INTO CURATED.SALES
SELECT *
FROM SALES_STREAM;

ALTER TASK SALES_TASK RESUME;